server:
  port: 8013

spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'#暴露要监控的所有端点，actuator中的，雷神springboot最后有讲