server:
  port: 8003

spring:
  application:
    name: service-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_h_demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    password: Haworthia0715
    username: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #所有entities所在的包
  type-aliases-package: com.atlisheng.cloud.entities

#eureka配置信息
eureka:
  client:
    #将当前服务注册到EurekaServer中
    register-with-eureka: true
    #从EurekaServer抓取已有注册信息，默认为true，单节点无所谓，集群必须设置为true配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka
      #集群版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #actuator设置服务列表Status服务名
    instance-id: payment8003
    #actuator设置服务列表Status服务鼠标悬停浏览器左下角显示ip和端口
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后的等待时间上限，单位为秒（默认是90s），超时将剔除服务
    lease-expiration-duration-in-seconds: 2
