server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称，会用于其他服务对Eureka Server的访问，用于指定Eureka服务器的ip
  client:
    #register-with-eureka为false表示不想注册中心注册自己，默认就是false
    register-with-eureka: false
    #fetch-registry为false表示自己端就是注册中心，职责是维护服务实例，不需要去检索查询调用服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要该地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
