server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#设置feign客户端超时时间（OpenFeign默认支持ribbon，为什么使用ribbon的参数进行控制，在02模块中只是使用ribbon设置负载均衡策略，但是发送请求还是单独使用的RestTemplate）
ribbon:
  #建立连接所用时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务端读取到可用资源所用的时间
  ConnectTimeout: 5000


logging:
  level:
    #feign日志以debug几倍监控服务调用接口PaymentServiceClient，这个是spring日志的debug级别监控PaymentServiceClient接口的full级别的信息
    com.atlisheng.cloud.client.PaymentServiceClient: debug